### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by bjlittle** [informatics-lab/forest#128]
After https://github.com/informatics-lab/forest/issues/111 is addressed, enable code test coverage

**Comment by bjlittle** [comment]
@andrewgryan I don't think that you've turned on https://coveralls.io/ for this repo, or have you?

**Comment by andrewgryan** [comment]
Not yet, I'll try it now

**Comment by bjlittle** [comment]
I use my GitHub account to sign-in. Then it should sync your GitHub repos i.e., coveralls.io will establish what repos you have forked or own (left handside menu, "Add Repos"), then turn-on forest.

If you need a hand, just let me know :+1:

**Comment by andrewgryan** [comment]
I think I've done it!

**Comment by bjlittle** [comment]
Cool!

For each repo, there will also be a "details" button from the "add repos", but in the top left-hand-corner there is also a "settings" for the repo, which amongst other things allows you to control the pull request alerts from coveralls.io, such as "Coverage threshold for failure" and "Coverage decrease threshold for failure".... this means that the PR can be marked as not good to merge if the testing coverage has decreased below a minimum threshold or by a % amount. This is useful once you get up to about 90+% and you want to maintain that level of coverage.

Let's see if it kicks in on the next PR request :crossed_fingers:

**Comment by andrewgryan** [comment]
That's very useful, it's good to have an automated way to encourage people to write tests

**Comment by bjlittle** [comment]
Closed by #136
