### ISSUE TITLE
Add units to mouse-over pop-up

### ISSUE THREAD

**Issue by rhattersley** [informatics-lab/forest#131]
Append the units of measure to the "Value" in the mouse-over pop-up.
![image](https://user-images.githubusercontent.com/917914/65516368-d20ed380-ded8-11e9-8cae-35e258ad4870.png)

**Comment by CarolineBain** [comment]
Thanks Richard, going to have a go at this one

**Comment by andrewgryan** [comment]
This is a good time to tidy up the naming convention of the View and Loader classes responsible for plotting images too! And to add plenty of API docs

**Comment by rhattersley** [comment]
> This is a good time to tidy up the naming convention of the View and Loader classes responsible for plotting images too! And to add plenty of API docs

+1 for consistent names + docs, but except for ensuring new methods have docs (and possibly adding docs to updated methods), I'd suggest doing those in separate pull request(s).

**Comment by andrewgryan** [comment]
@rhattersley exactly, code we touch while implementing units can get docs but a more dedicated documentation effort would be a separate pull request and naturally beyond the scope of this issue

**Comment by CarolineBain** [comment]
I have added a test called test_units.py and made the changes to the DBLoader and the view.... just checking it all works now

**Comment by CarolineBain** [comment]
Wooo done #165 closes this issue

**Comment by rhattersley** [comment]
> Wooo done #165 closes this issue

Although that's now one less small-change issue ready for the hackathon... 😛

**Comment by andrewgryan** [comment]
Yes, but now @CarolineBain has wicked GitHub and TDD skills!
