### ISSUE TITLE
Broken tutorial

### ISSUE THREAD

**Issue by andrewgryan** [informatics-lab/forest#156]
Both James Groves and @rhattersley have found a problem with the tutorial, the `--config-file` example populates the menu system but does not display an image. I suspect this is an untested path in `main.py`

**Comment by rhattersley** [comment]
It relates to the use of `args.files` when [creating the locator](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/main.py#L130). This value is empty when the UM files are only described by the config file.

**Comment by andrewgryan** [comment]
Thanks @rhattersley that whole code block could do with some simplification and extraction

**Comment by andrewgryan** [comment]
The code from line [108](https://github.com/informatics-lab/forest/blob/b0745e84bd655a98e08ae39a5f0275e4fedb84e4/forest/main.py#L108) to line 147 seems to be initialising the LOADERS dict which you've already mentioned needs a refactor #154

**Comment by lecjlg** [comment]
Line 95 of the tutorial references config.yml but this file doesn't exist. The 
`forest-tutorial . ` command creates a file called config.yaml.
This could lead to confusion for users?

**Comment by lecjlg** [comment]
Line 111 states run the following command, but the command is missing.

**Comment by andrewgryan** [comment]
Thanks @lecjlg I'll tidy up the tutorial instructions and make less confusing file names appear when `forest-tutorial .` is run

**Comment by andrewgryan** [comment]
@rhattersley I've extracted a method (a5a271c759cb83289c07dcfb062d9decb7a63a59) and intend to use a test-driven builder design pattern to solve the problem of configuring a loader/locator for combinations of database/pattern/files and for each supported file type

**Comment by andrewgryan** [comment]
OK I've reproduced the issue in a test suite and have the nuts and bolts to simplify the design so that there the rules for creating locators and loaders along with their file system patterns and directories are simple for the user to follow.

As it stands, I tried to allow users to mix and match `--directory` with `pattern` and `directory` settings inside the `config.yml`

```yaml
files:
   - label: My experiment
     pattern: "*.nc"
     directory: leaf/dir
```

The above when run with `--directory=/some/prefix`, should produce `/some/prefix/leaf/dir/*.nc`
Which I guess is probably a bit complicated to grok

**Comment by andrewgryan** [comment]
91811ca31db81f9a43a705563a3c1fdf78f4a67a highlights the steps involved to get it working. I think it should be much clearer what is going on so I might spend some time writing API docs and implementing the desired functionality test-first to make the design simpler

**Comment by andrewgryan** [comment]
Maybe the command line argument should be `--prefix-dir` or something, which might make things clearer to the user

**Comment by andrewgryan** [comment]
And maybe a clearer distinction between a list of files and a pattern. Since a pattern can be refreshed and can encode more information such as date patterns
