### ISSUE TITLE
Plot CMIP6 data in FOREST

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/forest#189]
Work by NCAR has made some of the CMIP6 data available through an intake catalogue, partly at a hackathon in October 2019
Hackathon: https://cmip6hack.github.io/#/
intake-esm: https://github.com/NCAR/intake-esm

This issue aims to implement a module to visualise remotely stored CMIP6 data. This can become a template for visualising remote datasets specified through an intake catalogue.

**Comment by stevehadd** [comment]
Development branch: https://github.com/informatics-lab/forest/tree/ems-intake

**Comment by stevehadd** [comment]
At 4033626 (folloowing the hackaton), the following functionalty is in place:
* read metadata from intake catalogue
* get selected data through intake and zarr. 
* plot data for one experiment/institution/member combo for air temperature.
tasks remaining:
* selection of variable and updating plot
* docstrings & code styling

**Comment by andrewgryan** [comment]
@stevehadd great job! This looks very promising. I'm looking forward to the pull request

**Comment by stevehadd** [comment]
I found the issue described in #207 while testing this code. There is temporary fix in the code in the PR #195 .

**Comment by stevehadd** [comment]
The PR #195 has now been merged, so we can close this issue.
