### ISSUE TITLE
Improve Bokeh widgets

### ISSUE THREAD

**Issue by GAndrsn** [informatics-lab/forest#2]
Currently, dropdown menus of date strings or sliders of integers are used for selecting dates, rather than a date slider. 

Also, Short dropdown menus are used where only a couple of options are available, in which case radio buttons might be preferable.

In the Sim Im vs. Himawari-8 app, the dropdown menu for selecting the wavelength only shows single letter references (i.e. 'W' for Water Vapour), as this refers to dictionary keys to the data. Having something more descriptive would be preferable.

I've put these together as one issue, as they will all require similar solutions, based on improving understanding of Bokeh widgets.

**Comment by GAndrsn** [comment]
I don't know of a simple guide to all widgets, but the Bokeh reference on bokeh.models.widgets will be comprehensive if not concise:

https://bokeh.pydata.org/en/latest/docs/reference/models.html

**Comment by GAndrsn** [comment]
Details of how to use the most useful-looking Bokeh widgets:

![image](https://user-images.githubusercontent.com/32956809/35037935-ed9f3e2a-fb70-11e7-85f7-2012cfd5ad4f.png)

**Comment by GAndrsn** [comment]
It is worth noting that different versions of Bokeh have different modules for widgets.

- The CDN version is 0.12.4, which does not have date sliders, among other things.
- The Jade version is 0.12.10, which has date sliders, but isn't the most recent version.
- The EC2 version is 0.12.13.

This was found to be an issue on Jade, where using conda to upgrade to 0.12.13 stopped plots appearing in the notebook.

**Comment by GAndrsn** [comment]
The attached Notebook demonstrates the apprent most useful widgets.

[bokeh_widget_testing.zip](https://github.com/met-office-lab/model_evaluation_tool/files/1639574/bokeh_widget_testing.zip)

**Comment by GAndrsn** [comment]
RadioGroupButton widget applied to Model vs IMERG app. Same widget type to be applied to wavelength selection in Sim Im vs Himawari-8 app. Then apply DateSlider to all apps.

**Comment by GAndrsn** [comment]
It turns out that the Bokeh version on EC2 is actually 0.12.4, preventing the use of DateSliders. If we want DateSliders, this needs updated.

**Comment by GAndrsn** [comment]
Using the MacBook allows for the combination of Bokeh Server run from a terminal and Bokeh v0.12.10, so that the output of DateSliders can be checked in the terminal.

**Comment by GAndrsn** [comment]
Date and hour sliders now added to Sim Im vs Himawari-8 app. Will add the same sliders to other apps. Would be good to have a single, continuous datetime slider, but at the moment I can't see a way to do this.

**Comment by GAndrsn** [comment]
This example might be useful for coming up with a custom datetime slider widget, I'll come back to it at some point:

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/widget.html

**Comment by tam203** [comment]
Just to say that we should be able to update the AWS version of bokeh easily and I would of thought that we could solve the issues that your having with jupyterhub and versions to (maybe a new kernel as @stevehadd did).

More generally it might be worth creating a conda.env file to pin down what versions we need of what and to make it easy to recreate the environment.

**Comment by stevehadd** [comment]
I thought I'd tag onto this issue, that we should have more human reable labels for the dropdowns in the two model comparison app.

**Comment by GAndrsn** [comment]
Specific issues have now been created, but this issue will be kept open as it contains useful information.

- [ ] #38 
- [ ] #46 
- [ ] #47

**Comment by stevehadd** [comment]
These issues have been dealt with, or split into other issues so closing this issue.
