### ISSUE TITLE
Add string.Template support to allow flexibility over config settings

### ISSUE THREAD

**Issue by andrewgryan** [informatics-lab/forest#213]
The current `--directory` flag is unintuitive. It mangles the `pattern` parameter in the locator settings in an implicit way. A better approach would be to allow the user to set variables themselves

```yaml
...
pattern: ${prefix}/leaf/dir/*.nc
...
```

And then on the command line, either use environment variables or keyword arguments.

E.g.  `--var 'prefix:/some/dir'` or `export prefix=/some/dir` to inject values into the config.yaml

```yaml
...
pattern: /some/dir/leaf/dir/*.nc
...
```
That way settings are explicit and the user decides which aspects of their config is changeable at run time.

**Comment by andrewgryan** [comment]
Environment variable support allows for the following syntax `pattern: ${HOME}/some/*.json` which is quite nice and saves the labour intensive `--var "x:${HOME}"` with `pattern: ${x}/some/*.json`

**Comment by andrewgryan** [comment]
Allowing this functionality means we need to use `yaml.safe_load` since `yaml.load` can execute arbitrary Python

**Comment by rhattersley** [comment]
> Allowing this functionality means we need to use `yaml.safe_load`

Don't we need to use safe_load even now?

**Comment by andrewgryan** [comment]
Yes, we do. But I thought I'd add that comment as a reminder.

**Comment by andrewgryan** [comment]
#214 PR closes this issue
