### ISSUE TITLE
Include additional rainfall accumulation field

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/forest#23]
Include rainfall accumulation fields in model/model and model/GPM plots. Possible:
* 6hr
* 12hr
* 24hr

**Comment by GAndrsn** [comment]
Rainfall accumulations for 6/12/24 hour time windows are now available in Model vs GPM app. This issue also suggests adding accumulations to Model/Model. This shouldbe be too difficult, as the current implemenation simply involves creating new variables by summing existing precipitation data, which was inspired by how Model/Model creates extra wind variables.

**Comment by stevehadd** [comment]
We also need to consider changing the colour scale for longer periods, as the totals tend to saturate at the top end.

**Comment by stevehadd** [comment]
The accumulations are now in model/GPM and 2 model apps. Creating a separate issue (#64) for colourscales.
