### ISSUE TITLE
Rename Observable.subscribe to Observable.add_subscriber

### ISSUE THREAD

**Issue by twsearle** [informatics-lab/forest#259]
I reckon this is a bit clearer as to which way `Observable.subscribe` is running. Rather than the Observable going away to subscribe to the arguments list of subscribers, it is taking the argument and adding it to its own list of subscribers.

**Comment by andrewgryan** [comment]
@twsearle agreed, I'll submit a PR to rename `Observable.subscribe` to `Observable.add_subscriber` which, as you point out, makes it easier to reason about
