### ISSUE TITLE
Setup a requirements file

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/forest#27]
Currently, the dependencies that need to me installed for forest to run are not clearly documented anywhere. This should be put together into some sort of requirements file, which will set up the environment for forest in a single command (hopefully!).

**Comment by tam203** [comment]
He. I would say that these dependencies should be captured in the docker container build file. I think that then the only requirement is Docker and also fuse-lib / mac-fuse.

What should be done though is to go through and make sure everything in the docker container is versioned i.e. `conda install iris-1.4 numpy=2.3` (numbers made up) else you don't know what your are going to get.

**Comment by stevehadd** [comment]
I have now added a setup file at forest_lib/forest_setup.sh.
