### ISSUE TITLE
Make profile & time-series tools optional

### ISSUE THREAD

**Issue by rhattersley** [informatics-lab/forest#280]
Make them default to OFF (i.e. the tools are not available in the UI), but allow them to be turned ON (e.g. by configuration).

**Comment by andrewgryan** [comment]
@rhattersley this has been implemented but the default is ON unless explicitly turned off in the config file. I can see the merits of both approaches. Perhaps setting a default ON/OFF per feature is more appropriate?

**Comment by rhattersley** [comment]
The most important thing is the ability to turn off things that are still experimental/not ready for general release and that capability now exists. Whether it defaults to ON or OFF, and whether the default is global or feature-specific is far less important - i.e. I wouldn't worry about it right now.

Hence, **I suggest we just close this issue**.

We can always open a fresh issue if/when the question of feature-specific defaults arises again.
