### ISSUE TITLE
BUG: unified_model.nc no longer produces content on server. 

### ISSUE THREAD

**Issue by wolfiex** [informatics-lab/forest#343]
When running forest with the tutorial data, it serves a blank (contentless) window following the commit below.  

Run command:
 `forest --show unified_model.nc` 
  where unified_model is generated by forest-tutorial. 
I have kept this separate just to be on the safe side, eventhough this has not changed through the commits.

I have been through the most recent commits and narrowed the break between the two below. @andrewgryan have you any idea what might be causing this?

Last working commit:
a14dfe8f550fac6b831cf6a46e5111aaaa3ee41a (Merge pull request #320 from eardkdw/master )

First broken commit:
3f98c90bb11d17618fef621292f5177258c76f30 (culmination of many attempts to trace memory leak)
and all others following it.

**Comment by andrewgryan** [comment]
@wolfiex this is working in the most recent state of `master`. I think the issue was I made middleware more general for EIDA50 satellite to lazy load it on click but inadvertently swallowed all actions when not viewing EIDA50, I corrected it by putting in a missing `yield action` statement

**Comment by andrewgryan** [comment]
8b36d922991d81e86801df74b878c1be1df0b02c was the fix to pass on actions not related to navigation

**Comment by wolfiex** [comment]
Ah yes.  I'll close the issue.
