### ISSUE TITLE
Box Zoom causes distortion (incorrect aspect ratio)

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/forest#66]
There is a box zoom tool provided by bokeh, but when using this tool, the data selected matches exactly the rectangle chosen by the user, if even if it is a long, thin rectangle, and the data is then streched to fit the display. As a result the plot can be horribly distorted. We need to find a way to ensure that box zoom rather selects an appropriate shape subset of data to display, using wither the width or the height of the user specified rectangle.

**Comment by andrewgryan** [comment]
This issue is solved by #72 by using `bokeh.plotting.figure(..., match_aspect=True)`. The slider branch moves to a single figure layout so is not an exact solution to this issue but may be sufficient for our purposes

**Comment by andrewgryan** [comment]
We no longer use a box zoom tool to navigate, so this ticket can be closed
