### ISSUE TITLE
Display coastlines using bokeh

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/forest#67]
Currently, coastlines are added to the forest plots at the matplotlib stage of plotting, thus they are rasterised before sending to bokeh and quickly look blocky when zooming in. @GAndrsn has developed some code to use cartopy coastlines, but plotted directly in bokeh to improve this.
```
import cartopy.feature as cf
p = figure()

for val in cf.COASTLINE.geometries():
    coast_lons, coast_lats = val[0].xy
    p.line(coast_lons, coast_lats, color='red')
```
We should replace the existing coastline code with this. This is in keeping with the longer term goal to plot more data e.g. station data using bokeh directly.

**Comment by andrewgryan** [comment]
This approach could prove useful for the  **hi-res zoom** #74 developments. Moving away from rasterizing canvases and towards rasterizing individual `pcolormesh` and `imshow` scalar mappables opens the door for native bokeh coastlines and figure features. Pixelated artefacts from rasterizing matplotlib canvases should be avoidable moving forward

**Comment by andrewgryan** [comment]
Vector coastlines, lakes and country boundaries have been in FOREST for some time now
