### ISSUE TITLE
Bokeh "Gantt Chart" vis and control

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/forest#71]
To help the user understand and select what is being viewed, we should create a gant chart type visualisation with associated sliders. Key design point will be:
* a 2d plot showing what data is avaiable for each model run at different lead times
* slider is available for all data times available, even if some of the datasets not available for that time
* select data time on hourly basis, then select window (aggregations) or nearest data point based on that.
* vertical slider for selecting for switching model runs

**Comment by andrewgryan** [comment]
I implemented and trialled this approach with @claretandy and @CarolineBain but it produced an unintuitive user experience, the current FOREST navigation system is an old-fashioned but intuitive dropdown/button experience
