### ISSUE TITLE
Single figure with slider design

### ISSUE THREAD

**Issue by andrewgryan** [informatics-lab/forest#72]
# Forest slider feature

The future of Forest is a full screen interface where the comparisons are performed on a pixel by pixel basis. Integrating a slider feature to work alongside the existing box zoom and pan tools might require some experimentation. To prevent clashes with the other buttons/tools, being able to activate/deactivate the slider is desirable

## Full screen constant aspect ratio

Bokeh has full screen responsive figures built in to the library through `sizing_mode="stretch_both"` keyword argument given to `bokeh.plotting.figure()`. It also has a built in feature to keep the aspect ratio constant, in our case 1:1 is the default, `match_aspect=True`

Note: These features are orthogonal to this ticket but are the settings to be used when designing the SliderTool

## SliderTool

The implementation in my personal github pages uses 3 HoverTools with CustomJS callbacks, 1 to show the left image, 1 to show the right and 1 to draw a vertical line at the interface

See, https://github.com/andrewgryan/bokeh-playground/blob/master/windy_forest/main.py for more details

For the Forest tool I would like to clean up my prototype, document it better with some useful unit tests and perhaps add some extra UI to make it integrate nicely with the existing Forest UI

## Single Figure layout

Some work might be needed to decouple the existing design from the number of bokeh Figure instances.

**Comment by andrewgryan** [comment]
I started  a branch [forest_72_slider](/informatics-lab/forest/tree/forest_72_slider) to implement slider and Forest layout re-design

**Comment by andrewgryan** [comment]
Simulated imagery is a beast to work with and burns out my tiny little macbook.

I have noticed there is a nice zoom method in scipy (`scipy.ndimage.zoom`) that makes it easier to sub-sample imagery without coarsifying the result too much. My naive approach was to sub-sample along the array `[::n, ::n]`. This should make Forest run much faster without impacting the user and also opens the door for adding a callback to make the images higher resolution on zoom

**Comment by andrewgryan** [comment]
## Zoom/render feature

After some experimentation to make a lightweight app to test my slider I hit upon the idea of doing a Google Maps style zoom and overlay high resolution imagery. The collection of high resolution patches can be managed in some way to limit the memory overhead that bokeh has to deal with

This design impacts the ultimate implementation of the slider, as the slider has to manage collections of rgba images not just the two that it currently supports

**Comment by andrewgryan** [comment]
There should also be some checking to prevent needless overlaying of existing high-res patches

**Comment by andrewgryan** [comment]
The **Zoom** tool is the last piece of the puzzle for this ticket, bear with me. I know an extra tool makes this ticket harder to review but since the Zoom tool needs to integrate with the Slider it is more efficient to work on both in the same branch

**Comment by andrewgryan** [comment]
The **hi-res zoom overlay** feature is not mature enough for release version `0.2.0` it has been shelved until release `0.3.0` . A new issue #74 has been opened to deal with it

**Comment by andrewgryan** [comment]
All zoom code has been removed 760213f and migrated to [forest_74_zoom](/informatics-lab/forest/tree/forest_74_zoom) related to issue #74

**Comment by andrewgryan** [comment]
This issue is painfully close to review. When a region is selected the RGBA images are reset but the Toggle mechanism and to some extent the Slider are failing to handle the change gracefully

**Comment by stevehadd** [comment]
The changes have now been merged into the master in PR #79. I restarted the server so forestdev would run with the merged version. Something seems to have gone wrong though, and although the GUI appears fine, the images are not displaying on the server, though the merged master worked fine locally. There is no error message from the kubernetes logs, so could you take a look to see what might be going wrong?

**Comment by andrewgryan** [comment]
I don't think anything is going wrong, I think we just need to zoom out. I'm cleaning up how Forest deals with axis limits by removing the matplotlib Figure dependency and allowing ForestPlot to control the Bokeh `figure.x_range` and `figure.y_range` directly in #74
