### ISSUE TITLE
create conda environment file

### ISSUE THREAD

**Issue by tam203** [informatics-lab/forest#80]
Currently the readme lists some things to install but not their versions and it likely misses some. 

We should check in a conda environment file or `requirements.txt` pip file or something.

**Comment by andrewgryan** [comment]
6e5877cfbf5363d3642c032f36cdfff2627d793e I added the output from `conda env export > environment.yml` to the branch [forest_80_conda_env](/informatics-lab/forest/tree/forest_80_conda_env)

This might contain more than we need but hopefully will be a first step towards a `requirements.txt`

**Comment by bjlittle** [comment]
@andrewgryan Nice, but as a strategy this will easily go stale.

As an alternative approach is to have a `conda list --explicit` as part of the `travis-ci`, see [here](https://github.com/informatics-lab/forest/pull/126/files#diff-354f30a63fb0907d4ad57269548329e3R41).

The benefit is two-fold:

- It's easy for a developer to recreate the `travis-ci` environment locally for debugging etc
- It acts as a reference on `master` of the explicit environment that works

I'm going to fold the removal of the `conda-spec.txt` into https://github.com/informatics-lab/forest/pull/126 to push this agenda, and close this issue.
