### ISSUE TITLE
README run instructions say EXPORT mean export as EXPORT isn't a function

### ISSUE THREAD

**Issue by meganfitzsimons** [informatics-lab/forest#85]
They could also do with the path to `forest_lib` rather than <path to the forest lib>

**Comment by andrewgryan** [comment]
Well spotted!

**Comment by rhattersley** [comment]
This issue can be closed. It was fixed by 1d056c5daf9270212471f2c592e53e7593c54611, but was also subsequently rendered obsolete.

**Comment by andrewgryan** [comment]
Agreed, there are plenty of stale issues that should be closed
